### PR TITLE
Updated NRT Callsign

### PR DESCRIPTION
**Pull request by NickNac113**
NRT used to belong to charter airline in Spain. Charter airline is defunct, now a travel company with cruise line charters. Callsign still exists in ICAO and IATA documentation.

Changed to active VA Callsign for Northern Reliable Transport, Callsign Reliable. set value for VA to true.

### CODE REVIEW

**Comment by maiuswong** [comment]
Thank you, but I am not accepting updates to airlines.json for VAs at this time.

**Comment by NickNac113** [comment]
May I ask why, or at least when you will be accepting updates? There are lots of VAs with the VA tag already on there. Some even with manual markers to show dual callsign?

**Comment by maiuswong** [comment]
Because there is no line to be drawn.  Anyone could build a website, get 2 pilots, and ask to be added to SimAware.  VATSIM will be rewriting the rules on VA partners shortly, and then I might consider it.  But right now, I have received dozens of requests, some to the point of incessant badgering, that I have lost any interest in pursuing this.

**Comment by NickNac113** [comment]
Understood. Sorry to hear that. I am a member of your Patreon. I will keep an eye out there in case this changes.

**Pull request closed without merging**
